# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no

  sandbox-cpp:
    build:
      context: .
      dockerfile: sandbox/judge-cpp.Dockerfile
    image: sandbox-cpp

  sandbox-python:
    build:
      context: .
      dockerfile: sandbox/judge-python.Dockerfile
    image: sandbox-python

  judge-worker:
    build: .
    env_file: .env
    depends_on:
      - redis
      - sandbox-cpp
      - sandbox-python
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 512M 


# networks:
#   judge-net:
#     driver: bridge