# docker-compose.yml
version: '3.8'

services:
  sandbox-cpp:
    build:
      context: .
      dockerfile: sandbox/judge-cpp.Dockerfile
    image: judge-cpp

  sandbox-python:
    build:
      context: .
      dockerfile: sandbox/judge-python.Dockerfile
    image: judge-python

  judge-worker:
    build: .
    env_file: .env
    depends_on:
      - sandbox-cpp
      - sandbox-python
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    deploy:
      resources:
        limits:
          memory: 512M 


# networks:
#   judge-net:
#     driver: bridge